services:
  aleebot:
    image: aleebot
    volumes:
      - ./database.sqlite:/usr/src/bot/database.sqlite
      - ./.env:/usr/src/bot/.env
    ports:
        - "3000:3000"
  web:
    image: aleebot-web
    environment:
      - HOST=0.0.0.0
    ports:
      - "4321:4321"
