const { abVersion } = require("./settings.json");
const { version } = require("discord.js");

const activities = [
    `AleeBot ${abVersion}`,
    'Coding bytes',
    'Drawing shapes',
    'Fighting Quad',
    'Installing Windows 11',
    'Breaking Windows 10',
    'Beating up big tech',
    'Deleting Google',
    'Watering down the Apple walled garden',
    'Reticulating splines',
    'Generating world',
    'Never punch a tree...',
    'Collecting data',
    'Dag dag!',
    'Developed by Andrew Lee',
    'When will 2.13 release?',
    'Alert Irruption !!!',
    'when',
    'Frying Shrimpbot',
    'RADIATION BABY',
    'Frivolously Spending',
    'Thanks! @Victor',
    'MCA DiscoVision',
    'Werq',
    'Pombo',
    'Ian Clary\'s First Day At FrivoloCo!',
    'Squid Airlines',
    'AirCS Race',
    'FrivoloCo',
    'I WANT 2 ORDER',
    'I REALLY WANT 2 ORDER',
    'I SAID I WANT 2 ORDER',
    'THANK YOU FOR TAKING SO LONG',
    'I COULD HAVE DONE THAT 67% FASTA',
    'I DO NOT WANT 2 ORDER ANYMORE',
    'Monica Is Going To Cosume You',
    'BLÅHAJ',
    'ShiftOS',
    'Histacom',
    'Wall Street',
    'Abunchoo 12.10',
    'MikeOS',
    'theBeat',
    'FRESHMusicPlayer',
    'theShell',
    'theBeat',
    'theSlate',
    'theDesk',
    'Ultra Jump Mania!',
    'Battle Blaze',
    'Tempest',
    'Turbo Crash 9',
    'Pocket Gakusei',
    'Hidden Heroes',
    'Skybreakers',
    'Always Running',
    'Only Up',
    'Trade',
    'Breeze',
    'Steady',
    'Bluejay',
    'Exposing TAS-Corp',
    'Fighting Evelyn Claythorne',
    'Hacking SherCorp',
    'Games with Tari',
    'Decommissioning Meta Runners',
    'Installing Meta Runners',
    '90% bug free!',
    'Google Wallet',
    'Apple Pay',
    'Splatoon 3',
    'Super Mario 64',
    `Now running on Discord.JS ${version}!`
];

exports.activity = activities
