const { abVersion } = require("./settings.json");
const { version } = require("discord.js");

const activities = [
    `AleeBot ${abVersion}`,
    'Coding bytes',
    'Drawing shapes',
    'Fighting Quad',
    'Installing Windows 11',
    'Breaking Windows 10',
    'Beating up big tech',
    'Deleting Google',
    'Deleting Apple',
    'Deleting System32',
    'Deleting /usr/bin/',
    'Watering down the Apple walled garden',
    'Reticulating splines',
    'Generating world',
    'Never punch a tree...',
    'Collecting data',
    'Dag dag!',
    'Developed by Andrew Lee',
    'When will 2.13 release?',
    'Alert Irruption !!!',
    'when',
    'Frying Shrimpbot',
    'RADIATION BABY',
    'Frivolously Spending',
    'Thanks! @Victor',
    'MCA DiscoVision',
    'Werq',
    'Pombo',
    'Ian Clary\'s First Day At FrivoloCo!',
    'Squid Airlines',
    'AirCS Race',
    'FrivoloCo',
    'I WANT 2 ORDER',
    'I REALLY WANT 2 ORDER',
    'Monica Is Going To Cosume You',
    'BLÅHAJ',
    'ShiftOS',
    'Histacom',
    'Wall Street',
    'Mac OS X Jaguar',
    'Abunchoo 12.10',
    'MikeOS',
    'theBeat',
    'FRESHMusicPlayer',
    'theShell',
    'theBeat',
    'theSlate',
    'theDesk',
    'Ultra Jump Mania!',
    'Battle Blaze',
    'Tempest',
    'Turbo Crash 9',
    'Pocket Gakusei',
    'Hidden Heroes',
    'Skybreakers',
    'Always Running',
    'Only Up',
    'Trade',
    'Breeze',
    'Steady',
    'Bluejay',
    'Exposing TAS-Corp',
    'Fighting Evelyn Claythorne',
    'Frying Dr. Sheridan',
    'Hacking SherCorp',
    'Games with Tari',
    'Decommissioning Meta Runners',
    'Installing Meta Runners',
    '90% bug free!',
    'Google Wallet',
    'Apple Pay',
    'Splatoon 3',
    'Super Mario 64',
    'Minceraft',
    'Mario Kart 8',
    'bnbmc',
    'Evaluating JavaScript code',
    'Evaluating C# code',
    'Forkbombing FMP',
    'Merging with DLAP',
    'Now asbestos-free!',
    'May contain nuts!',
    'MythOS',
    'Also try Scratch!',
    'Funky!',
    'Apple Vision Pro',
    'What is Web3?',
    'GNU\'s NOT UNIX!',
    'Linux, but actually GNU/Linux',
    'Debloating my ThinkPad',
    'Turbotastic!',
    `Now running on Discord.JS ${version}!`
];

exports.activity = activities
