const settings = require("./settings.json");
const Discord = require("discord.js");

const activities = [
    `AleeBot ${settings.abVersion}`,
    'Coding bytes',
    'Drawing shapes',
    'Fighting Quad',
    'Ultra Jump Mania!',
    'Battle Blaze',
    'Tempest',
    'Turbo Crash 9',
    'Pocket Gakusei',
    'Hidden Heroes',
    'Skybreakers',
    'Exposing TAS-Corp',
    'Fighting Evelyn Claythorne',
    'Games with Tari',
    'Decommissioning Meta Runners',
    'Installing Meta Runners',
    'Installing Windows 11',
    'Breaking Windows 10',
    'Reticulating splines',
    'Generating terrain',
    'Never punch a tree...',
    'Collecting data',
    'Dag dag!',
    'Developed by Andrew Lee',
    'When will 2.13 release?',
    'Alert Irruption !!!',
    'when',
    'Thanks! @Victor',
    'Pombo',
    'AirCS Race',
    'ShiftOS',
    'Histacom',
    'theBeat',
    'FRESHMusicPlayer',
    'theShell',
    'theBeat',
    'theSlate',
    'Google Wallet',
    'Ian Clary\'s First Day At FrivoloCo!',
    'Squid Airlines',
    'Beating up big tech',
    'Deleting Google',
    'Watering down the Apple walled garden',
    'Frying Shrimpbot',
    '90% bug free!',
    'Now running ' + Discord.version + '!'
];

exports.activity = activities
